version: '3.8'
services:
  chat:
    container_name: chat-app
    image: python:3.9-slim
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TABLE=${MYSQL_TABLE}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
      apt install python3-pip
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt &&
      gunicorn --bind 0.0.0.0:5000 app:app"
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge